### ISSUE TITLE
Milestone1 - Section 1: Motivation and Purpose

### ISSUE THREAD

**Issue by hchqin** [UBC-MDS/DSCI-532_2024_17_Global-CO2-Emissions-Tracker#1]
In a few sentences, provide motivation for why you are creating a dashboard:

- Who is your target audience, and what role are you embodying?
- What is the problem the target audience is facing and why is it important to solve?
- How can your dashboard assist in solving this problem for the intended target audience?

For details, please refer to [milestone1.md](https://github.ubc.ca/MDS-2023-24/DSCI_532_milestone1_group17/blob/master/milestone1.md)

**Comment by Jing-19** [comment]
@jokittipong

**Comment by jokittipong** [comment]
In a few sentences, provide motivation for why you are creating a dashboard:

Who is your target audience, and what role are you embodying?
The general public with an interest in the environment is our target audience. We are a team of UNEP (UN Environment Programme) officers and Intergovernmental Panel on Climate Change (IPCC) officers who want to raise concern about CO2 emissions.

What is the problem the target audience is facing and why is it important to solve?
The target audience faces the problem of increasing CO2 emissions, leading to climate change, air pollution, ocean acidification, and socio-economic impacts. It's crucial to solve this issue to protect the environment, human health, and ensure a sustainable future for all.

How can your dashboard assist in solving this problem for the intended target audience?

A CO2 emission data dashboard can give our target audience overview by providing real-time information on global CO2 emissions, sources and trends. This dashboard will help individuals to understand and feel the magnitude of this problem. They can track progress and be informed and can use it to assist on making decisions about personal and collective actions to reduce emissions. The CO2 data dashboard helps people understand CO2 emissions better by showing information in an easy-to-understand way. This makes people more aware of the problem, encourages them to take responsibility, and gets them involved in finding solutions to reduce CO2 emissions.

For details, please refer to [milestone1.md](https://github.ubc.ca/MDS-2023-24/DSCI_532_milestone1_group17/blob/master/milestone1.md)
