### ISSUE TITLE
Milestone1 - Section 4: App sketch & brief description

### ISSUE THREAD

**Issue by hchqin** [UBC-MDS/DSCI-532_2024_17_Global-CO2-Emissions-Tracker#4]
Create a sketch of what you envision your app to look like. Your sketch can be hand-drawn or put together using a graphics editor or slide show software. The sketch should be saved as img/sketch.png and linked in this section of the proposal so that the image shows up when reading the proposal on GitHub.

Complement the sketch with a high level description of the main components in the app interface and how the user will interact with it. You are not required to use terminology specific to Dash/Shiny (i.e. widgets, components, etc...).

For details, please refer to [milestone1.md](https://github.ubc.ca/MDS-2023-24/DSCI_532_milestone1_group17/blob/master/milestone1.md)

**Comment by Jing-19** [comment]
@Jing-19
