### ISSUE TITLE
Feedback from Joel

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_17_Global-CO2-Emissions-Tracker#43]
Major:
- [ ]  Zoom in to countries when selected. E.g. filter df?
- [ ] Select from map as well
- [x] #45
    - [x] #47

Minor:
- [x] #48
- [x] #49
    - [x] #50
- [x] #46
    - [x] Maybe center?
    - [x] Maybe some spacing the nto widtets

**Comment by Jing-19** [comment]
"Select from map as well" is addressed in m4 #71
