### ISSUE TITLE
Feedback from Ruocong Sun

### ISSUE THREAD

**Issue by sungg888** [UBC-MDS/DSCI-532_2024_17_Global-CO2-Emissions-Tracker#54]
Good job group 17! 
I am impressed by the informative dashboard you have created. It is intuitive and user-friendly. Also it is easy to understand with the interface. My feedback is as follows:

1: For the upper left world map, it is a little confusing with the "Total_Emissions" bar if I only select one country. For example, when I select only China, the bar show the color from light to dark and also with different scales but those scales are very similar numbers. I felt it is confusing with the title called total emissions(should have one number if there is only one country selected) and also have many numbers on the bar for one country. My suggesting is to only show one number if user only selected one country. And show the number on the side of bar with corresponding color if possible. 

2: For the bottom right plot, it will be more clear if it can show the same color as the upper plot for each top 5 countries. Since these two plots are interactive, and showing similar information, it is common that users will look side by side for comparison. Therefore, if they have the same color for the same country, it will be more clear and easy to identify from both plots. 

3: I noticed that when I select one country, this country will be highlighted on the world map with more information such as total emissions, average, std, max and min. This is a very good idea to show more information to users. However, if I select some small countries and want to read more information about them such as "Cabo verde" or "Andorra", it is hard to find on map.  I am not sure if there are some ways to highlight those countries so user can find them easily, feel free to ignore this if it is not feasible. 

4: For the upper right plot, it might be better if you can reorganize the pie chart and the country names because sometimes the country name list block the percentage number. For example, if you select "Latine America & Caribbean", we cannot see the complete percentage for Mexico(only show "29."). 
 
Thank you

**Comment by Jing-19** [comment]
feedback has been summarized in #59
