### ISSUE TITLE
Feedback from Thomas Jian

### ISSUE THREAD

**Issue by 786213750** [UBC-MDS/DSCI-532_2024_17_Global-CO2-Emissions-Tracker#55]
Great work, Group 17! I'm thoroughly impressed with the dashboard you've put together—it's both intuitive and easy to navigate, making it a user-friendly tool for data visualization. Here’s my feedback:

1. Displaying all country as the landing page is little bit messy so consider removing some of the country as landing page.
2. A more clear indication or highlight on the year selector, right now it is easy to miss.
3. The title should be centered and the styling can be added.
4. The top value in the bar chart is cut off partially by the frame of the graph.
5. The pie chart and bar chart need labels indicating that they show the sum of all years of CO2 emission values by country.

Thank you for your continuous effort to improve this tool—it’s shaping up to be an excellent resource for data visualization.

**Comment by Jing-19** [comment]
feedback has been summarized in #59
