### ISSUE TITLE
Feedback from Ziwei Chen

### ISSUE THREAD

**Issue by czwcandy** [UBC-MDS/DSCI-532_2024_17_Global-CO2-Emissions-Tracker#57]
Great job Group 17. I am truly impressed by your dashboard. It is wonderful and user-friendly. Your team shows a lot of different graphs in this dashboard. Different plots shows different functions. After using your dashboard, I come to realized the situation in past year of different countries. 
My feedback are below:
1. For charts, especially when showing multiple countries, consider dynamic scaling or log scales if there's a wide variance in values to ensure smaller values are still visible. I am not sure if there is any corner case. If there's not, please ignore.
2. Clearly label all axes and provide a legend or notation for any units of measurement used.
3. Adding indicators such as "Most Improved" or "Highest Emitter" could provide quick insights and drive user engagement.
4. For the country selection, a search bar could be helpful for quickly locating a country instead of scrolling through the dropdown list.

**Comment by Jing-19** [comment]
feedback has been summarized in #59
